"""remove old property and listing tables

Revision ID: d518a0754fa4
Revises: 8a1b2c3d4e5f
Create Date: 2026-08-21 10:43:06.007927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd518a0754fa4'
down_revision = '8a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('listing_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('bhk', sa.INTEGER(), nullable=True),
    sa.Column('area', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('locality', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('amenities', sa.TEXT(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=500), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'OWNER'"), nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('video_filename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('listing_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('city_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('area', sa.VARCHAR(length=100), nullable=True),
    sa.Column('specifications', sa.TEXT(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
